# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: OpenInfra Days Korea 2018
email: master@openinfradays.kr
description: OpenInfra Days Korea 2018
baseurl: "/2018" # the subpath of your site, e.g. /blog
url: "https://openstack-kr.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Usernames and API Keys
github_username: openstack-kr
gmaps_embed_api_key: AIzaSyCwJbDHw2P7_Ao6M9ksYn68ZiISwfLCF3E

# Location & time
period: "2018년 6월 28-29일 오전 9:00 ~ 오후 6:00"
location: "COEX 3층 컨퍼런스룸E (구 Hall E)"
address: "서울특별시 강남구 봉은사로 524"
location_query: "COEX KOREA"

# Event Sponsors
hosts:
  - name: OpenStack 한국 커뮤니티
    image: openstack-korea.png
    url: http://www.openstack.or.kr
    desc: >
      -
  - name: OpenStack Foundation
    image: openstack.png
    url: https://www.openstack.org
    desc: >
      -
  - name: CNCF 한국 커뮤니티
    image: cncf-korea-community.png
    url: https://www.meetup.com/Cloud-Native-Computing-Seoul/
    desc: >
      -
runs:
  - name: OpenStack 한국 커뮤니티
    image: openstack-korea.png
    url: http://www.openstack.or.kr
    desc: >
      -
  - name: OpenStack Foundation
    image: openstack.png
    url: https://www.openstack.org
    desc: >
      -
  - name: 한국정보통신산업진흥원
    image: nipa.png
    url: https://www.nipa.kr
    desc: >
      -
platinums:
  - name: NetApp
    image: netapp.png
    url: https://www.netapp.co.kr/
    desc: >
      -
  - name: SK Telecom
    image: skt.png
    url: http://www.sktelecom.co.kr/
    desc: >
      -
  - name: 맨텍
    image: mantech.png
    url: http://www.mantech.co.kr/
    desc: >
      -
  - name: 오픈소스컨설팅
    image: osic.png
    url: http://www.osci.kr/
    desc: >
      -
  - name: 삼성전자
    image: samsung.png
    url: http://www.samsung.com/sec/
    desc: >
      -
  - name: Cloud Native Foundation
    image: CNCF.png
    url: https://www.cncf.io/
    desc: >
      -
golds:
  - name: SUSE
    image: suse.png
    url: https://www.suse.com/
    desc: >
      -
  - name: HP Enterprise
    image: hpe.png
    url: https://www.hpe.com/kr/ko/home.html
    desc: >
      -
  - name: MTOS
    image: mtos.png
    url: http://www.mtos.co.kr/
    desc: >
      -
  - name: Nokia
    image: nokia.jpg
    url: https://networks.nokia.com/
    desc: >
      -
  - name: SPTek
    image: sptek.jpg
    url: http://www.sptek.co.kr/
    desc: >
      -
  - name: ATTO Research
    image: atto-research.png
    url: http://www.atto-research.com
    desc: >
      -
  - name: KINX
    image: kinx.jpg
    url: https://www.kinx.net/
    desc: >
      -
silvers:
  - name: OpenStack Foundation
    image: openstack.png
    url: https://www.openstack.org
    desc: >
      -
  - name: Innogrid & Westpac
    image: innogrid-westpac.png
    url: 
    desc: >
      -
  - name: LINE
    image: line.jpg
    url: 
    desc: >
      -
  - name: 엑세스랩
    image: xslab.png
    url: 
    desc: >
      -
  - name: 에덴파트너스코리아
    image: edenpartnerskorea.png
    url: https://edenchain.io/
    desc: >
      -
  - name: ""
    image: ""
    url: ""
    desc: >
      -
      
sponsors:
  - name: CUBRID
    image: cubrid.png
    url: http://www.cubrid.com/
    desc: >
      네임택 후원
  - name: NCloud24
    image: ncloud24.png
    url: https://www.ncloud24.com/
    desc: >
      실습 VM 후원
  - name: Open Networking Foudnation
    image: onf.png
    url: https://www.opennetworking.org/
    desc: >
      - 커뮤니티 후원
  - name: IBM
    image: ibm.png
    url: https://www.ibm.com/kr-ko/
    desc: >
      - 핸즈온랩 후원
  - name: ""
    image: ""
    url: ""
    desc: >
      -     

medias:
  - name: 디지털데일리
    image: media-digital-daily.gif
    url: http://www.ddaily.co.kr/
    desc: >
      미디어 후원
  - name: 네트워크타임즈
    image: media-network-times.jpg
    url: http://www.datanet.co.kr/
    desc: >
      미디어 후원
  - name: 아크로팬
    image: media-acrofan.jpg
    url: http://kr.acrofan.com/
    desc: >
      미디어 후원
  - name: ZDNet
    image: media-zdnet.png
    url: http://zdnet.co.kr
    desc: >
      미디어 후원
  - name: 한빛미디어
    image: book-hanbit.png
    url: http://www.hanbit.co.kr/media/
    desc: >
      책 후원
  - name: 길벗
    image: book-gilbut.jpg
    url: https://www.gilbut.co.kr/
    desc: >
      책 후원

# license
owner: "MeltingCon Community Alliance"
code_license: "MIT"
copyright: Copyright (c) 2018 OpenStack Korea User Group All Rights Reserved.
content_license: "CC BY-SA 4.0"

# Custom Collection
collections:
  session1s:
    title: Sessions (day 1)
    output: true
    permalink: "/session1/:path"
  session2s:
    title: Sessions (day 2)
    output: true
    permalink: "/session2/:path"
  workshop2s:
    title: Workshops (day 2)
    output: true
    permalink: "/workshop2/:path"

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
